/**
 * Programmatic operational FAQ catalog for Zare (~1000 guide entries).
 * Each entry is a HelpArticle-shaped object merged into HELP_ARTICLES.
 * Zare uses these for keyword retrieval — not neural training.
 */

/** @typedef {{ id: string; title: string; keywords: string[]; answer: string; steps: string[]; links: Array<{ label: string; to: string; state?: object }> }} HelpArticle */

const GUIDE_FOOTER =
  ' Zare explains the SOP only — you perform saves, approvals, and postings in Zarewa yourself.';

/** @type {Array<{ module: string; action: string; title: string; answer: string; steps: string[]; links: Array<{ label: string; to: string; state?: object }>; extraKeywords?: string[] }>} */
const OPERATIONAL_TOPICS = [
  // —— Sales (15 × 10 = 150) ——
  {
    module: 'sales',
    action: 'record a customer payment receipt',
    title: 'Record a customer payment (receipt)',
    answer: 'Receipts are recorded against an approved quotation from Sales → Payments.',
    steps: [
      'Open **Sales** → **Payments** (receipts).',
      'Click **Record payment** and select the quotation.',
      'Enter amount, date, and treasury account split.',
      'Save — you post the receipt; Zare does not.',
    ],
    links: [{ label: 'Sales — Payments', to: '/sales', state: { focusSalesTab: 'receipts' } }],
    extraKeywords: ['receipt', 'payment', 'customer paid'],
  },
  {
    module: 'sales',
    action: 'create a new quotation',
    title: 'Create a quotation',
    answer: 'Quotations capture products, pricing, and terms before payment or production.',
    steps: [
      'Open **Sales** → **Quotations** → **New**.',
      'Select customer, branch, lines, and pricing.',
      'Save draft or submit for approval per branch policy.',
    ],
    links: [{ label: 'Sales — Quotations', to: '/sales', state: { focusSalesTab: 'quotations' } }],
    extraKeywords: ['quote', 'quotation', 'new sale'],
  },
  {
    module: 'sales',
    action: 'edit a quotation before approval',
    title: 'Edit a quotation (draft)',
    answer: 'Draft quotations can be edited until approved or restricted by role.',
    steps: [
      'Open the quotation from **Sales** → **Quotations**.',
      'Use **Edit** if your role allows and status is draft.',
      'If locked, request **edit approval** from a manager.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['change quote', 'modify quotation'],
  },
  {
    module: 'sales',
    action: 'add a cutting list',
    title: 'Add a cutting list',
    answer: 'Cutting lists link production metres to a quotation after payment thresholds.',
    steps: [
      'Open **Sales** → **Cutting list** tab.',
      'Select quotation and enter line metres.',
      'Save — production may start when policy is met.',
    ],
    links: [{ label: 'Sales — Cutting list', to: '/sales', state: { focusSalesTab: 'cuttinglist' } }],
    extraKeywords: ['cutting', 'metres', 'production prep'],
  },
  {
    module: 'sales',
    action: 'submit a refund request',
    title: 'Submit a customer refund request',
    answer: 'Refund requests need quotation context, lines, and payee details.',
    steps: [
      'Open **Sales** → **Refunds** → **New**.',
      'Select quotation and enter breakdown lines.',
      'Complete payee bank details and submit for approval.',
    ],
    links: [{ label: 'Sales — Refunds', to: '/sales', state: { focusSalesTab: 'refund' } }],
    extraKeywords: ['refund', 'return money', 'customer refund'],
  },
  {
    module: 'sales',
    action: 'understand refund approval rules',
    title: 'Refund approval rules (guide)',
    answer: 'Managers with refunds.approve (or finance.approve) approve in Sales or Manager inbox — Zare only explains who can.',
    steps: [
      'Open the pending refund and review breakdown vs paid amount.',
      'A manager uses **Approve** or **Reject** in Zarewa — not in chat.',
      'After approval, Finance may record treasury payout.',
    ],
    links: [{ label: 'Manager dashboard', to: '/manager' }],
    extraKeywords: ['approve refund', 'who approves refund'],
  },
  {
    module: 'sales',
    action: 'record customer advance deposit',
    title: 'Customer advance (deposit)',
    answer: 'Advance payments are tracked separately from quotation allocation.',
    steps: [
      'Use receipt flow and mark advance/deposit per screen labels.',
      'Confirm treasury account and customer match.',
      'Allocate to quotations when sales processes payment.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['advance', 'deposit', 'customer balance'],
  },
  {
    module: 'sales',
    action: 'handle customer overpayment on a quotation',
    title: 'Customer overpayment / credit on quotation',
    answer: 'Overpayments may auto-apply as credit per branch rules.',
    steps: [
      'Review quotation paid vs total on **Sales**.',
      'Check branch policy for auto-credit.',
      'Finance may reconcile if treasury mismatch.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['overpaid', 'excess payment', 'credit'],
  },
  {
    module: 'sales',
    action: 'handle below-floor pricing on a quotation',
    title: 'Below-floor pricing exception',
    answer: 'Below-floor quotes need branch manager approval before production; MD may confirm before refund.',
    steps: [
      'See pricing exception panel on the quotation.',
      'Branch manager approves exception when eligible.',
      'After production, MD confirmation may be required before refund.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['floor price', 'discount', 'price exception'],
  },
  {
    module: 'sales',
    action: 'find a quotation or receipt by reference',
    title: 'Find QT / RCP / RF by search',
    answer: 'Use the header search with QT-, RCP-, or RF- prefixes.',
    steps: [
      'Click global search (top bar).',
      'Type reference e.g. QT-2024-001 or RCP-…',
      'Open the document from results.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['search', 'find quote', 'find receipt'],
  },
  {
    module: 'sales',
    action: 'fix a wrong amount on a receipt',
    title: 'Wrong receipt amount (guide)',
    answer: 'Depends on posted status — edit in Sales if allowed, else correction memo + Finance.',
    steps: [
      'Open receipt — if still editable, fix amount and save.',
      'If posted to ledger, do not silently change — use reversal/correction workflow.',
      'Raise **Payment correction memo** for manager/Finance.',
    ],
    links: [{ label: 'Sales — Payments', to: '/sales', state: { focusSalesTab: 'receipts' } }],
    extraKeywords: ['wrong amount', 'mistake receipt', 'correct receipt'],
  },
  {
    module: 'sales',
    action: 'fix payment posted to wrong customer',
    title: 'Wrong customer on payment',
    answer: 'Wrong customer posting needs controlled correction — not a quick edit after ledger post.',
    steps: [
      'Stop further receipts on the wrong quote until reviewed.',
      'Notify Finance and branch manager.',
      'Use correction memo / reversal per Finance SOP.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['wrong customer', 'misallocated payment'],
  },
  {
    module: 'sales',
    action: 'report a duplicate receipt',
    title: 'Duplicate receipt',
    answer: 'Duplicate receipts may need reversal of one line — Finance verifies treasury.',
    steps: [
      'Identify both RCP references.',
      'Do not delete posted rows — follow reversal SOP.',
      'Raise duplicate receipt memo to Finance.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['duplicate receipt', 'posted twice'],
  },
  {
    module: 'sales',
    action: 'cancel or void a quotation',
    title: 'Cancel a quotation',
    answer: 'Cancellation rules depend on payments and production status.',
    steps: [
      'Open quotation and check paid amount and jobs.',
      'Use cancel/void only if role and status allow.',
      'Refunds may be required if money was collected.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['void quote', 'cancel quotation'],
  },
  {
    module: 'sales',
    action: 'understand payment threshold before production',
    title: 'Payment threshold before production',
    answer: 'Branch policy may require minimum collection % before cutting list or production.',
    steps: [
      'Check quotation paid % on Sales detail.',
      'Collect receipts until threshold met.',
      'Operations sees unlock when sales/manager rules satisfied.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['threshold', 'minimum payment', 'before production'],
  },

  // —— Finance (15 × 10 = 150) ——
  {
    module: 'finance',
    action: 'record an expense',
    title: 'Record an expense',
    answer: 'Expenses may be direct or linked to payment requests.',
    steps: [
      'Open **Finance** → relevant expenses tab.',
      'Enter category, amount, branch, and proof.',
      'Submit or save per your role.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['expense', 'spend', 'cost'],
  },
  {
    module: 'finance',
    action: 'submit an expense payment request',
    title: 'Submit expense payment request',
    answer: 'Payment requests route for finance.approve before treasury payout.',
    steps: [
      'Create request with lines, category, and attachment.',
      'Submit for approval — manager/finance approves in Zarewa.',
      'After approved, record **Payout** from treasury when cash leaves bank.',
    ],
    links: [{ label: 'Finance — Payments', to: '/accounts', state: { accountsTab: 'disbursements' } }],
    extraKeywords: ['payment request', 'expense request', 'pay vendor'],
  },
  {
    module: 'finance',
    action: 'understand who can approve a payment request',
    title: 'Payment request approval rules',
    answer: 'finance.approve permission is required — Zare explains; a finance user clicks Approve.',
    steps: [
      'Check your role in **Settings → Team & access**.',
      'Approver opens Manager or Finance queue.',
      'They use Approve/Reject — not Zare.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['approve payment request', 'cannot approve expense'],
  },
  {
    module: 'finance',
    action: 'record treasury payout for approved request',
    title: 'Treasury payout (approved request)',
    answer: 'Payout records money leaving bank/cash after approval.',
    steps: [
      'Finance → **Payments** or treasury queue.',
      'Open approved request → **Payout**.',
      'Select bank/cash account and confirm amount.',
    ],
    links: [{ label: 'Finance', to: '/accounts', state: { accountsTab: 'treasury' } }],
    extraKeywords: ['payout', 'pay from treasury', 'disburse'],
  },
  {
    module: 'finance',
    action: 'reconcile bank lines to receipts',
    title: 'Bank reconciliation',
    answer: 'Match external bank entries to ERP receipts and movements.',
    steps: [
      'Finance → **Receipts & recon** or bank queue.',
      'Add or match lines to receipts/treasury.',
      'Save reconciliation when balanced.',
    ],
    links: [{ label: 'Finance — Receipts', to: '/accounts', state: { accountsTab: 'receipts' } }],
    extraKeywords: ['bank recon', 'match bank', 'reconciliation'],
  },
  {
    module: 'finance',
    action: 'understand accounting period locked error',
    title: 'Period locked (PERIOD_LOCKED)',
    answer: 'Locked months block backdated posting — Finance may unlock in governance.',
    steps: [
      'Check voucher/receipt date period.',
      'Ask Finance to unlock period in **Settings → Governance** if appropriate.',
      'Use correction memo for posted mistakes instead of silent edits.',
    ],
    links: [{ label: 'Settings — Governance', to: '/settings/governance' }],
    extraKeywords: ['period locked', 'PERIOD_LOCKED', 'closed month'],
  },
  {
    module: 'finance',
    action: 'correct which bank account was used for payout',
    title: 'Pay-from account correction',
    answer: 'Finance roles with access may correct pay-from on posted treasury lines.',
    steps: [
      'Open posted outflow in **Payments** register.',
      'Use **Pay-from** or edit action if enabled.',
      'Document reason per audit policy.',
    ],
    links: [{ label: 'Finance — Payments', to: '/accounts', state: { accountsTab: 'disbursements' } }],
    extraKeywords: ['pay from', 'wrong bank account', 'treasury correction'],
  },
  {
    module: 'finance',
    action: 'pay a supplier accounts payable',
    title: 'Supplier / AP payment',
    answer: 'Supplier payments often link to PO or AP records and treasury.',
    steps: [
      'Locate PO or AP item in Finance/Procurement.',
      'Record payout with correct supplier reference.',
      'Attach proof of transfer.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['supplier payment', 'AP', 'accounts payable'],
  },
  {
    module: 'finance',
    action: 'pay an approved customer refund',
    title: 'Refund treasury payout',
    answer: 'Approved refunds appear in Finance awaiting payout queue.',
    steps: [
      'Finance → refunds awaiting payout.',
      'Verify payee account on refund.',
      'Record **Pay** from treasury.',
    ],
    links: [{ label: 'Finance', to: '/accounts', state: { accountsTab: 'treasury' } }],
    extraKeywords: ['refund payout', 'pay refund'],
  },
  {
    module: 'finance',
    action: 'cancel payment request before payout',
    title: 'Cancel payment request before pay',
    answer: 'Cancelled before treasury payout avoids double pay.',
    steps: [
      'Open approved/unpaid request.',
      'Use **Cancel** before payout if role allows.',
      'Confirm with requester.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['cancel request', 'stop payment'],
  },
  {
    module: 'finance',
    action: 'reverse a treasury payout',
    title: 'Reverse treasury payout',
    answer: 'finance.reverse may post compensating entries — use with control.',
    steps: [
      'Open paid request/line.',
      'Use **Reverse payout** if permission allows.',
      'Coordinate with audit — Zare only guides.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['reverse payout', 'undo payment'],
  },
  {
    module: 'finance',
    action: 'clearance a sales receipt in finance',
    title: 'Finance receipt clearance',
    answer: 'Finance confirms receipt against bank and delivery rules.',
    steps: [
      'Finance → pending clearance queue.',
      'Open receipt → **Confirm & reconcile** when matched.',
      'Cleared receipts affect refund eligibility rules.',
    ],
    links: [{ label: 'Finance — Receipts', to: '/accounts', state: { accountsTab: 'receipts' } }],
    extraKeywords: ['clearance', 'reconcile receipt'],
  },
  {
    module: 'finance',
    action: 'transfer between treasury accounts',
    title: 'Internal treasury transfer',
    answer: 'Moves balance between bank/cash accounts in same branch.',
    steps: [
      'Finance → **Treasury** → transfer.',
      'Select from/to accounts and amount.',
      'Post transfer — you confirm; Zare guides only.',
    ],
    links: [{ label: 'Finance — Treasury', to: '/accounts', state: { accountsTab: 'treasury' } }],
    extraKeywords: ['transfer', 'move cash', 'bank to bank'],
  },
  {
    module: 'finance',
    action: 'choose the right expense category',
    title: 'Expense category selection',
    answer: 'Categories affect reporting — use memo/request hints.',
    steps: [
      'Match spend type to chart category.',
      'Ask manager if unsure before posting.',
      'Use Zare memo assist for category suggestions only.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['expense category', 'classification'],
  },

  // —— Procurement (12 × 10 = 120) ——
  {
    module: 'procurement',
    action: 'create a purchase order',
    title: 'Create a purchase order',
    answer: 'POs may be coil, stone, or accessories — lines and supplier required.',
    steps: [
      '**Procurement** → **Purchases** → **New PO**.',
      'Select supplier, branch, lines, quantities.',
      'Submit for approval if required.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['PO', 'purchase order', 'buy stock'],
  },
  {
    module: 'procurement',
    action: 'understand purchase order approval rules',
    title: 'PO approval rules (guide)',
    answer: 'purchase_orders.manage or branch policy — approver clicks in Zarewa.',
    steps: [
      'Pending PO shows in approver queue.',
      'Approver reviews lines and supplier.',
      'Approve/Reject in UI — Zare explains rules only.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['approve PO', 'who approves purchase order'],
  },
  {
    module: 'procurement',
    action: 'receive goods on a GRN',
    title: 'Goods receipt (GRN)',
    answer: 'GRN confirms quantities received — may differ from ordered.',
    steps: [
      'Open approved PO → **GRN** / receive.',
      'Enter received qty/weight per line.',
      'Complete GRN to update stock.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['GRN', 'goods receipt', 'receive stock'],
  },
  {
    module: 'procurement',
    action: 'assign transport on a purchase order',
    title: 'PO transport / haulage',
    answer: 'Transport agent and fee link to PO for later treasury payout.',
    steps: [
      'Open PO → transport section.',
      'Enter transporter, reference, quoted fee.',
      'Finance pays haulage when status allows.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['transport', 'haulage', 'delivery PO'],
  },
  {
    module: 'procurement',
    action: 'create a stone-coated purchase order',
    title: 'Stone-coated PO',
    answer: 'Stone POs use flatsheet/m² lines — check workbook pricing.',
    steps: [
      'Procurement → new stone PO.',
      'Enter m²/qty per colour/design lines.',
      'Follow approval and GRN like other POs.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['stone', 'stone coated', 'flatsheet'],
  },
  {
    module: 'procurement',
    action: 'create a coil purchase order',
    title: 'Coil PO',
    answer: 'Coil POs track gauge, weight, and supplier coil reference.',
    steps: [
      'Select coil product lines and ordered weight.',
      'Submit PO and receive on GRN into coil register.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['coil', 'aluminium coil', 'steel coil'],
  },
  {
    module: 'procurement',
    action: 'order procurement accessories',
    title: 'Accessories PO',
    answer: 'Accessory lines use SKU/qty — link to production needs.',
    steps: [
      'Create accessories PO with supplier.',
      'GRN into accessory stock.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['accessory', 'screws', 'spare parts PO'],
  },
  {
    module: 'procurement',
    action: 'avoid duplicate supplier registration',
    title: 'Duplicate supplier blocked',
    answer: 'System may block duplicate supplier names — merge in master data.',
    steps: [
      'Search existing suppliers first.',
      'Use Settings/master data to reconcile duplicates.',
      'Ask admin if merge needed.',
    ],
    links: [{ label: 'Settings', to: '/settings' }],
    extraKeywords: ['duplicate supplier', 'supplier exists'],
  },
  {
    module: 'procurement',
    action: 'handle GRN short weight vs ordered',
    title: 'GRN short weight / variance',
    answer: 'Short receipt may trigger alerts — document variance.',
    steps: [
      'Enter actual received weight on GRN.',
      'Note variance reason on PO/GRN.',
      'Manager/ops may review material incident if damage.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['short weight', 'GRN variance', 'less than ordered'],
  },
  {
    module: 'procurement',
    action: 'reject a purchase order',
    title: 'Reject a PO',
    answer: 'Approver rejects with note — requester may revise and resubmit.',
    steps: [
      'Approver opens pending PO.',
      'Click **Reject** and enter reason.',
      'Requester edits and resubmits new revision if needed.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['reject PO', 'decline purchase order'],
  },
  {
    module: 'procurement',
    action: 'track in-transit purchase orders',
    title: 'In-transit PO status',
    answer: 'In-transit shows goods moving — coordinate with transport payout.',
    steps: [
      'Filter PO list for in-transit.',
      'Confirm transport details.',
      'GRN when physically received.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['in transit', 'on the way', 'shipping'],
  },
  {
    module: 'procurement',
    action: 'pay supplier for a purchase order',
    title: 'Pay supplier (PO)',
    answer: 'Often via Finance treasury after PO/GRN and approval.',
    steps: [
      'Confirm GRN and payable amount.',
      'Finance records supplier payout.',
      'Attach bank proof.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['pay supplier', 'settle PO'],
  },

  // —— Operations (12 × 10 = 120) ——
  {
    module: 'operations',
    action: 'start a production job',
    title: 'Start production job',
    answer: 'Jobs link to quotation/cutting list and consume materials.',
    steps: [
      '**Operations** → production queue.',
      'Open job → **Start** when materials ready.',
      'Record metres/output as you progress.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['production', 'start job', 'manufacturing'],
  },
  {
    module: 'operations',
    action: 'complete a production job',
    title: 'Complete production job',
    answer: 'Completion updates metres and may unlock delivery/refund rules.',
    steps: [
      'Enter final output metres and usage.',
      'Mark job **Complete**.',
      'Check accessory/coil deductions applied.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['complete job', 'finish production'],
  },
  {
    module: 'operations',
    action: 'report a coil material issue',
    title: 'Coil / material issue',
    answer: 'Incidents document damage, loss, or quality issues.',
    steps: [
      'Operations → material incidents → **New**.',
      'Describe issue, qty, and attach photos.',
      'Submit for manager approval.',
    ],
    links: [{ label: 'Material exceptions', to: '/material-exceptions' }],
    extraKeywords: ['coil issue', 'damaged coil', 'material incident'],
  },
  {
    module: 'operations',
    action: 'approve a material incident',
    title: 'Material incident approval rules',
    answer: 'Branch manager or operations authority approves in UI.',
    steps: [
      'Open pending incident.',
      'Review evidence.',
      'Approver clicks Approve — Zare explains eligibility only.',
    ],
    links: [{ label: 'Material exceptions', to: '/material-exceptions' }],
    extraKeywords: ['approve incident', 'material approval'],
  },
  {
    module: 'operations',
    action: 'receive stock into store GRN',
    title: 'Store GRN (operations)',
    answer: 'Store receipt updates inventory from procurement or transfers.',
    steps: [
      'Match GRN to PO reference.',
      'Confirm qty and location.',
      'Post GRN.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['store receive', 'warehouse GRN'],
  },
  {
    module: 'operations',
    action: 'understand stock adjustment permissions',
    title: 'Stock adjustment rules',
    answer: 'inventory.adjust is sensitive — often manager-controlled.',
    steps: [
      'Verify cycle count before adjust.',
      'Use adjustment screen with reason code.',
      'Manager may need to approve.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['stock adjust', 'inventory correction'],
  },
  {
    module: 'operations',
    action: 'use the production register',
    title: 'Production register',
    answer: 'Register tracks coils/jobs output by period.',
    steps: [
      'Open production register view.',
      'Filter branch and date.',
      'Export or reconcile with job completions.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['register', 'production log'],
  },
  {
    module: 'operations',
    action: 'record accessory usage on a job',
    title: 'Accessory usage on job',
    answer: 'Accessories deduct from stock when recorded on job.',
    steps: [
      'Open job → accessories tab.',
      'Enter SKU/qty used.',
      'Save with production progress.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['accessory usage', 'consumables job'],
  },
  {
    module: 'operations',
    action: 'handle coil substitution on a job',
    title: 'Coil substitution',
    answer: 'Substitutions must match gauge/policy — may affect quoting.',
    steps: [
      'Record substitution reason on job.',
      'Link alternate coil ID.',
      'Notify sales if customer quote affected.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['substitute coil', 'swap coil'],
  },
  {
    module: 'operations',
    action: 'handle delayed production',
    title: 'Delayed / stuck production',
    answer: 'Check material availability, approvals, and payment gates.',
    steps: [
      'Review job status and blockers list.',
      'Resolve missing materials or approvals.',
      'Update expected date in notes/memo.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['delay', 'stuck job', 'production late'],
  },
  {
    module: 'operations',
    action: 'cancel a production job',
    title: 'Cancel production job',
    answer: 'Cancellation may reverse reservations — check policy.',
    steps: [
      'Open job → cancel if status allows.',
      'Release coil/accessory reservations.',
      'Inform sales if quote still active.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['cancel job', 'stop production'],
  },
  {
    module: 'operations',
    action: 'record output metres on a job',
    title: 'Record production metres',
    answer: 'Metres drive billing, refunds, and completion.',
    steps: [
      'Enter actual metres per line.',
      'Save progress or complete job.',
      'Verify against cutting list.',
    ],
    links: [{ label: 'Operations', to: '/operations' }],
    extraKeywords: ['metres', 'output', 'production metres'],
  },

  // —— Manager (10 × 10 = 100) ——
  {
    module: 'manager',
    action: 'clear a quotation for production',
    title: 'Manager quotation clearance',
    answer: 'Clearance removes sales/manager holds on quotation.',
    steps: [
      'Manager dashboard → clearance queue.',
      'Review payment % and exceptions.',
      'Click **Clear** — you approve; Zare guides.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['clearance', 'clear quote', 'manager hold'],
  },
  {
    module: 'manager',
    action: 'review a refund in the manager inbox',
    title: 'Manager refund review',
    answer: 'Refund intel shows quote, production, and paid context.',
    steps: [
      'Manager → refunds queue.',
      'Open refund → review breakdown.',
      'Approve/Reject in Zarewa.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['manager refund', 'review refund'],
  },
  {
    module: 'manager',
    action: 'approve a payment request as finance',
    title: 'Manager/finance payment decision',
    answer: 'Payment requests need finance.approve — action in inbox.',
    steps: [
      'Open payment request detail.',
      'Verify attachment and amount.',
      'Approve or reject with note.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['payment decision', 'approve expense request'],
  },
  {
    module: 'manager',
    action: 'grant edit approval to a staff member',
    title: 'Edit approval token',
    answer: 'Locked edits need manager-issued edit approval ID.',
    steps: [
      'Staff requests edit on locked row.',
      'Manager → edit approvals → approve.',
      'Staff enters token to complete save.',
    ],
    links: [{ label: 'Edit approvals', to: '/edit-approvals' }],
    extraKeywords: ['edit approval', 'second approval', 'KPI code'],
  },
  {
    module: 'manager',
    action: 'review material incidents as manager',
    title: 'Manager material incidents',
    answer: 'Pending incidents show in manager/ops queues.',
    steps: [
      'Open incident detail and photos.',
      'Approve/reject or request more info via memo.',
    ],
    links: [{ label: 'Material exceptions', to: '/material-exceptions' }],
    extraKeywords: ['manager incident', 'material review'],
  },
  {
    module: 'manager',
    action: 'handle a flagged below-floor quote',
    title: 'Flagged quotation review',
    answer: 'Pricing exceptions need documented approval.',
    steps: [
      'Review margin/exception panel.',
      'Approve exception if within policy.',
      'Document remark for audit.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['flagged quote', 'price review'],
  },
  {
    module: 'manager',
    action: 'sign off conversion production review',
    title: 'Conversion review signoff',
    answer: 'Some jobs need manager signoff after conversion metrics.',
    steps: [
      'Manager → conversion queue.',
      'Enter remark (min length).',
      'Submit signoff.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['conversion', 'signoff', 'production review'],
  },
  {
    module: 'manager',
    action: 'use the manager attention dashboard',
    title: 'Manager attention dashboard',
    answer: 'Shows cross-module items needing action.',
    steps: [
      'Open **Manager** home.',
      'Work queues: clearance, refunds, payments.',
      'Click through to act in Zarewa.',
    ],
    links: [{ label: 'Manager', to: '/manager' }],
    extraKeywords: ['attention', 'manager dashboard', 'inbox'],
  },
  {
    module: 'manager',
    action: 'use KPI approval code for sensitive actions',
    title: 'KPI / second approval code',
    answer: 'Officers may need manager code for delete/reverse actions.',
    steps: [
      'Request code from manager.',
      'Manager issues via edit approval workflow.',
      'Enter code on Finance/action screen.',
    ],
    links: [{ label: 'Edit approvals', to: '/edit-approvals' }],
    extraKeywords: ['KPI code', 'approval code', 'second signoff'],
  },
  {
    module: 'manager',
    action: 'work across branches as manager',
    title: 'Branch scope for managers',
    answer: 'Approvals usually limited to assigned branch unless view-all.',
    steps: [
      'Check branch picker in header.',
      'Switch branch to see that queue.',
      'Cannot approve other branch without permission.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['branch', 'wrong branch approval', 'scope'],
  },

  // —— Settings & admin (10 × 10 = 100) ——
  {
    module: 'settings',
    action: 'register a new ERP login for staff',
    title: 'Register ERP user (Team & access)',
    answer: 'Admin creates logins in Settings — separate from HR employee file.',
    steps: [
      '**Settings** → **Team & access**.',
      '**Add user**: username, name, password, role, branch.',
      'User signs in and changes password if required.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['register staff', 'new user', 'create login'],
  },
  {
    module: 'settings',
    action: 'change user permissions',
    title: 'User permissions',
    answer: 'Granular permissions override role defaults.',
    steps: [
      'Team & access → select user.',
      'Edit permission checklist.',
      'Save — changes apply on next login/session refresh.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['permissions', 'access rights', 'role'],
  },
  {
    module: 'settings',
    action: 'reset a user password',
    title: 'Password reset (admin)',
    answer: 'Admins may reset passwords — user should change after login.',
    steps: [
      'Team & access → user row.',
      'Generate/set temporary password.',
      'Tell user to update under **Security**.',
    ],
    links: [{ label: 'Settings — Security', to: '/settings/security' }],
    extraKeywords: ['password', 'reset login', 'forgot password admin'],
  },
  {
    module: 'settings',
    action: 'lock or unlock accounting period',
    title: 'Governance period lock',
    answer: 'Locked periods block backdated finance posts.',
    steps: [
      '**Settings** → **Governance**.',
      'Select period → lock/unlock.',
      'Document reason for unlock.',
    ],
    links: [{ label: 'Settings — Governance', to: '/settings/governance' }],
    extraKeywords: ['lock period', 'unlock month', 'governance'],
  },
  {
    module: 'settings',
    action: 'switch workspace branch',
    title: 'Switch branch',
    answer: 'Header branch picker limits data to selected branch.',
    steps: [
      'Click branch name (top bar).',
      'Select branch or view-all if allowed.',
      'Refresh lists after switch.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['switch branch', 'change branch', 'BR-'],
  },
  {
    module: 'settings',
    action: 'maintain colour master list',
    title: 'Colour master data',
    answer: 'Consistent colour names prevent duplicate spellings on quotes.',
    steps: [
      'Settings → setup/master data colours.',
      'Add official names only.',
      'Train staff to pick from list.',
    ],
    links: [{ label: 'Settings', to: '/settings' }],
    extraKeywords: ['colour', 'color master', 'duplicate colour'],
  },
  {
    module: 'settings',
    action: 'sync material pricing workbook',
    title: 'Material workbook pricing',
    answer: 'Workbook prices drive quotation floors and exceptions.',
    steps: [
      'Settings/pricing ops per your role.',
      'Import or update workbook.',
      'Verify branch sees new prices.',
    ],
    links: [{ label: 'Settings', to: '/settings' }],
    extraKeywords: ['workbook', 'pricing', 'floor price data'],
  },
  {
    module: 'settings',
    action: 'review Zare knowledge gaps',
    title: 'Zare intelligence (admin)',
    answer: 'Shows unanswered questions — drafts need merge to guides.',
    steps: [
      'Settings → **Zare intelligence**.',
      'Review gaps and run analytics.',
      'Add approved text to helpKnowledge via developer deploy.',
    ],
    links: [{ label: 'Settings', to: '/settings', state: { tab: 'zare-intelligence' } }],
    extraKeywords: ['zare', 'help gaps', 'train zare'],
  },
  {
    module: 'settings',
    action: 'update my profile and security',
    title: 'Profile & security',
    answer: 'Users update display name and password.',
    steps: [
      'Settings → **Profile**.',
      'Settings → **Security** for password.',
      'Enable practices per company policy.',
    ],
    links: [{ label: 'Settings', to: '/settings/security' }],
    extraKeywords: ['profile', 'my password', 'security'],
  },
  {
    module: 'settings',
    action: 'understand role templates',
    title: 'Role templates',
    answer: 'Roles bundle permissions — customize per user if needed.',
    steps: [
      'Review role list in Team & access.',
      'Assign closest role to new users.',
      'Add/remove individual permissions.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['role', 'sales staff', 'finance manager role'],
  },

  // —— HR (10 × 10 = 100) ——
  {
    module: 'hr',
    action: 'register a new employee in HR',
    title: 'HR employee register',
    answer: 'HR record is separate from ERP login — link policies per SOP.',
    steps: [
      'Open **HR** → **Staff register**.',
      'Enter employee details and branch.',
      'Create ERP login separately in Settings if needed.',
    ],
    links: [{ label: 'HR — Staff', to: '/hr/staff' }],
    extraKeywords: ['HR register', 'new employee', 'hire'],
  },
  {
    module: 'hr',
    action: 'view an employee HR profile',
    title: 'HR staff profile',
    answer: 'Profile holds employment data — sensitive fields may need unlock.',
    steps: [
      'HR → staff directory → open person.',
      'Use tabs for history, documents.',
      'Request sensitive unlock if masked.',
    ],
    links: [{ label: 'HR', to: '/hr' }],
    extraKeywords: ['staff profile', 'employee file'],
  },
  {
    module: 'hr',
    action: 'submit a leave request',
    title: 'Leave request',
    answer: 'Leave routes to approver per HR policy.',
    steps: [
      'HR → leave → new request.',
      'Enter dates and type.',
      'Approver acts in HR — not Zare.',
    ],
    links: [{ label: 'HR — Leave', to: '/hr/leave' }],
    extraKeywords: ['leave', 'annual leave', 'time off'],
  },
  {
    module: 'hr',
    action: 'record attendance',
    title: 'Attendance',
    answer: 'Daily roll or attendance capture per branch HR process.',
    steps: [
      'HR → attendance.',
      'Select date/branch.',
      'Mark present/absent.',
    ],
    links: [{ label: 'HR — Attendance', to: '/hr/attendance' }],
    extraKeywords: ['attendance', 'daily roll', 'present'],
  },
  {
    module: 'hr',
    action: 'run payroll',
    title: 'Payroll run',
    answer: 'Payroll is sensitive — HR/finance roles only.',
    steps: [
      'HR → payroll period.',
      'Validate attendance/deductions.',
      'Post payroll per SOP.',
    ],
    links: [{ label: 'HR — Payroll', to: '/hr/payroll' }],
    extraKeywords: ['payroll', 'salary run', 'pay staff'],
  },
  {
    module: 'hr',
    action: 'transfer staff between branches',
    title: 'Staff transfer',
    answer: 'Updates HR assignment — may need ERP branch/role update too.',
    steps: [
      'HR → transfers.',
      'Create transfer effective date.',
      'Update ERP user branch in Settings.',
    ],
    links: [{ label: 'HR — Transfers', to: '/hr/transfers' }],
    extraKeywords: ['transfer', 'move employee branch'],
  },
  {
    module: 'hr',
    action: 'record a discipline case',
    title: 'Discipline record',
    answer: 'Document incidents per HR policy — confidential.',
    steps: [
      'HR → discipline → new case.',
      'Enter facts and outcomes.',
      'Restrict visibility per role.',
    ],
    links: [{ label: 'HR', to: '/hr' }],
    extraKeywords: ['discipline', 'warning', 'HR case'],
  },
  {
    module: 'hr',
    action: 'use salary matrix',
    title: 'Salary matrix',
    answer: 'Matrix guides pay grades — not automatic payroll post.',
    steps: [
      'HR → salary matrix.',
      'Lookup grade for role/level.',
      'Apply in payroll manually per rules.',
    ],
    links: [{ label: 'HR', to: '/hr' }],
    extraKeywords: ['salary matrix', 'pay grade'],
  },
  {
    module: 'hr',
    action: 'unlock sensitive HR fields',
    title: 'Sensitive HR unlock',
    answer: 'Some fields masked until manager/HR unlock with reason.',
    steps: [
      'Click unlock on sensitive section.',
      'Enter approval reason.',
      'Access logs for audit.',
    ],
    links: [{ label: 'HR', to: '/hr' }],
    extraKeywords: ['sensitive', 'unlock HR', 'masked salary'],
  },
  {
    module: 'hr',
    action: 'understand HR record vs ERP login',
    title: 'HR employee vs ERP user',
    answer: 'HR = people record; Settings Team = system login. Both may be needed for new hire.',
    steps: [
      'Complete HR staff register first.',
      'Then Settings → Team & access for login.',
      'Keep names/branch consistent.',
    ],
    links: [
      { label: 'HR — Staff', to: '/hr/staff' },
      { label: 'Settings — Team', to: '/settings/team' },
    ],
    extraKeywords: ['HR vs ERP', 'employee vs user', 'two systems'],
  },

  // —— Workspace & memos (10 × 10 = 100) ——
  {
    module: 'workspace',
    action: 'compose an internal memo',
    title: 'Compose memo',
    answer: 'Memos route for approval and may convert to expense/PO.',
    steps: [
      'Workspace → **Compose memo**.',
      'Choose type, subject, body, attachments.',
      'Submit — you send; Zare can suggest wording only.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['memo', 'compose', 'internal memo'],
  },
  {
    module: 'workspace',
    action: 'file a memo after approval',
    title: 'File memo',
    answer: 'Filing closes the memo loop for audit.',
    steps: [
      'Open approved memo thread.',
      'Use **File** with category/reference.',
      'Confirm filing metadata.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['file memo', 'filing', 'archive memo'],
  },
  {
    module: 'workspace',
    action: 'choose memo routing',
    title: 'Memo routing',
    answer: 'Route lists who must approve (BM, Finance, etc.).',
    steps: [
      'Select memo type — route auto-suggests.',
      'Adjust recipients if policy allows.',
      'Submit for approval.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['route memo', 'who receives memo'],
  },
  {
    module: 'workspace',
    action: 'convert memo to expense request',
    title: 'Memo to expense',
    answer: 'Some memos convert to expense after approval.',
    steps: [
      'Open approved memo.',
      'Click **Convert to expense** if shown.',
      'Complete expense fields and submit.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['memo to expense', 'convert expense'],
  },
  {
    module: 'workspace',
    action: 'convert memo to procurement',
    title: 'Memo to procurement',
    answer: 'Procurement conversion starts PO/request from memo context.',
    steps: [
      'Approved memo → convert procurement.',
      'Fill supplier/items.',
      'Continue in Procurement module.',
    ],
    links: [{ label: 'Procurement', to: '/procurement' }],
    extraKeywords: ['memo to PO', 'procurement conversion'],
  },
  {
    module: 'workspace',
    action: 'reply in a memo thread',
    title: 'Reply in memo thread',
    answer: 'Thread keeps audit trail of conversation.',
    steps: [
      'Open memo from inbox.',
      'Type reply and attach if needed.',
      'Send — visible to recipients.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['reply memo', 'thread', 'comment'],
  },
  {
    module: 'workspace',
    action: 'find unfiled memos',
    title: 'Unfiled memos',
    answer: 'Unfiled items remain in attention queues.',
    steps: [
      'Workspace filter → unfiled.',
      'Complete filing for each.',
      'Or escalate via new memo.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['unfiled', 'pending filing'],
  },
  {
    module: 'workspace',
    action: 'search workspace items',
    title: 'Search workspace',
    answer: 'Search finds memos, approvals, and work items.',
    steps: [
      'Use workspace search or global search.',
      'Enter reference or keywords.',
      'Open item from results.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['search workspace', 'find memo'],
  },
  {
    module: 'workspace',
    action: 'use workspace command center',
    title: 'Workspace command center',
    answer: 'Command center aggregates inbox, approvals, and counts.',
    steps: [
      'Open **Workspace** home.',
      'Review folders: inbox, approvals, filed.',
      'Drill into category filters.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['command center', 'inbox', 'work items'],
  },
  {
    module: 'workspace',
    action: 'attach proof to a memo',
    title: 'Memo attachments',
    answer: 'Attachments required for many expense/diesel memos.',
    steps: [
      'Compose/edit memo → attach files.',
      'Verify upload succeeded.',
      'Approvers review attachments before approve.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['attachment', 'upload proof', 'document'],
  },

  // —— Memos / maintenance (8 × 10 = 80) ——
  {
    module: 'memo',
    action: 'raise a diesel or fuel memo',
    title: 'Diesel / fuel memo',
    answer: 'Fuel memos need litres, vendor, estimate, and approval.',
    steps: [
      'Compose → diesel/fuel type.',
      'Enter litres, vendor, amount.',
      'Route to Branch Manager.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['diesel', 'fuel', 'generator'],
  },
  {
    module: 'memo',
    action: 'raise a maintenance or repairs memo',
    title: 'Maintenance memo',
    answer: 'Attach mechanic quote or fault report.',
    steps: [
      'Compose → maintenance type.',
      'Describe fault and asset.',
      'Attach quote → submit.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['maintenance', 'repair', 'machine breakdown'],
  },
  {
    module: 'memo',
    action: 'raise a payment correction memo',
    title: 'Payment correction memo',
    answer: 'Use when posted payment/receipt wrong and needs controlled fix.',
    steps: [
      'Compose correction memo type.',
      'Reference RCP/transaction IDs.',
      'Route BM + Finance.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['correction memo', 'fix payment'],
  },
  {
    module: 'memo',
    action: 'request a receipt reversal',
    title: 'Receipt reversal request',
    answer: 'Reversals are Finance-controlled after review.',
    steps: [
      'Do not delete posted receipt.',
      'Memo with reversal template.',
      'Finance posts reversal in module.',
    ],
    links: [{ label: 'Finance', to: '/accounts' }],
    extraKeywords: ['reversal', 'reverse receipt'],
  },
  {
    module: 'memo',
    action: 'explain missing attachment blocker',
    title: 'Missing attachment',
    answer: 'Approval blocked until proof uploaded.',
    steps: [
      'Reopen memo/request.',
      'Attach PDF/image.',
      'Resubmit or notify approver.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['missing attachment', 'no file'],
  },
  {
    module: 'memo',
    action: 'understand read-only workspace',
    title: 'Read-only / offline workspace',
    answer: 'Reconnect when API offline — no mutations until back.',
    steps: [
      'Check network and login session.',
      'Refresh browser.',
      'Contact IT if persists.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['read only', 'offline', 'reconnect'],
  },
  {
    module: 'memo',
    action: 'use Zare for memo writing help only',
    title: 'Zare memo writing (guide only)',
    answer: 'Zare suggests wording/category — you submit memo yourself.',
    steps: [
      'Compose memo → Ask Zare bar.',
      'Use classify/formal/checklist chips.',
      'You click Submit when ready.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['zare memo', 'help write memo'],
  },
  {
    module: 'memo',
    action: 'track memo approval status',
    title: 'Memo approval status',
    answer: 'Status shows pending/approved/rejected — approvers act in UI.',
    steps: [
      'Open memo thread header.',
      'See approval chain.',
      'Follow up with approver outside chat if urgent.',
    ],
    links: [{ label: 'Workspace', to: '/' }],
    extraKeywords: ['memo status', 'pending approval memo'],
  },

  // —— General / Zare (10 × 10 = 100) ——
  {
    module: 'general',
    action: 'use global search in Zarewa',
    title: 'Global search',
    answer: 'Search finds documents by ID and keywords.',
    steps: [
      'Top bar search.',
      'Enter QT-, RCP-, memo ref, or keywords.',
      'Open result.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['search ERP', 'find document'],
  },
  {
    module: 'general',
    action: 'print a document or memo',
    title: 'Print document',
    answer: 'Print views available on many detail screens.',
    steps: [
      'Open document → print icon.',
      'Use browser print dialog.',
      'File printed copy per policy.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['print', 'PDF', 'hard copy'],
  },
  {
    module: 'general',
    action: 'run a management report',
    title: 'Reports',
    answer: 'Reports module exports operational/finance views.',
    steps: [
      'Open **Reports**.',
      'Select report and branch/period.',
      'Export if role allows.',
    ],
    links: [{ label: 'Reports', to: '/reports' }],
    extraKeywords: ['report', 'export', 'analytics export'],
  },
  {
    module: 'general',
    action: 'understand who can approve an item',
    title: 'Who can approve? (general)',
    answer: 'Depends on document type and permissions — Zare explains rules only.',
    steps: [
      'Ask Zare with document type context.',
      'Check Settings → Team for your permissions.',
      'Approver uses Approve in Zarewa — not chat.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['who approves', 'approval permission'],
  },
  {
    module: 'general',
    action: 'follow quote-to-cash workflow end to end',
    title: 'Quote-to-cash overview',
    answer: 'Quotation → payment → cutting list → production → delivery.',
    steps: [
      'Create quote (Sales).',
      'Collect receipts until threshold.',
      'Production → delivery → close quote.',
    ],
    links: [{ label: 'Sales', to: '/sales' }],
    extraKeywords: ['quote to cash', 'full workflow', 'end to end'],
  },
  {
    module: 'general',
    action: 'use Ask Zare help button',
    title: 'How to use Zare',
    answer: 'Zare is guide-only — SOPs, steps, approval rules. No posting in chat.',
    steps: [
      'Click life-ring **Zare** button.',
      'Ask how/why questions clearly.',
      'Rate answers with thumbs for learning.',
    ],
    links: [{ label: 'Settings', to: '/settings' }],
    extraKeywords: ['how to use zare', 'help bot', 'assistant'],
  },
  {
    module: 'general',
    action: 'fix permission denied 403',
    title: 'Permission denied',
    answer: 'Role lacks permission for action — ask admin or manager.',
    steps: [
      'Note exact screen and action.',
      'Check Settings → Team permissions.',
      'Request role update if job requires access.',
    ],
    links: [{ label: 'Settings — Team', to: '/settings/team' }],
    extraKeywords: ['403', 'permission denied', 'access denied'],
  },
  {
    module: 'general',
    action: 'understand branch vs company-wide view',
    title: 'Branch vs all branches',
    answer: 'view-all branches is restricted — most users see one branch.',
    steps: [
      'Check branch picker.',
      'MD/admin may view all.',
      'Reports respect branch filter.',
    ],
    links: [{ label: 'Dashboard', to: '/' }],
    extraKeywords: ['all branches', 'view all', 'branch filter'],
  },
  {
    module: 'general',
    action: 'recover from session expired',
    title: 'Session / login again',
    answer: 'Re-login restores permissions and branch context.',
    steps: [
      'Log out and log in.',
      'Select correct branch.',
      'Retry action.',
    ],
    links: [{ label: 'Login', to: '/login' }],
    extraKeywords: ['session', 'logged out', 'login again'],
  },
  {
    module: 'general',
    action: 'give feedback on a Zare answer',
    title: 'Rate Zare answers',
    answer: 'Thumbs up/down improves ranking for similar questions.',
    steps: [
      'After answer, click 👍 or 👎.',
      'Rephrase question if wrong topic.',
      'Admin reviews gaps in Zare intelligence.',
    ],
    links: [{ label: 'Settings', to: '/settings' }],
    extraKeywords: ['feedback zare', 'helpful', 'not helpful'],
  },
];

const QUESTION_TEMPLATES = [
  (action) => `how do i ${action}`,
  (action) => `how to ${action}`,
  (action) => `where do i ${action}`,
  (action) => `steps to ${action}`,
  (action) => `what is the process to ${action}`,
  (action) => `guide for ${action}`,
  (action) => `sop for ${action}`,
  (action) => `i need to ${action}`,
  (action) => `help me ${action}`,
  (action) => `explain how to ${action}`,
  (action) => `can i ${action} in zarewa`,
];

const MODULE_PATH = {
  sales: '/sales',
  finance: '/accounts',
  procurement: '/procurement',
  operations: '/operations',
  manager: '/manager',
  settings: '/settings',
  hr: '/hr',
  workspace: '/',
  memo: '/',
  general: '/',
};

/** Target catalog size (question phrasings × SOP topics). */
export const OPERATIONAL_FAQ_TARGET = 1000;

/**
 * Build operational FAQ articles (exactly {@link OPERATIONAL_FAQ_TARGET} entries).
 * @returns {HelpArticle[]}
 */
export function buildOperationalHelpArticles() {
  /** @type {HelpArticle[]} */
  const articles = [];
  let index = 0;

  outer: for (const topic of OPERATIONAL_TOPICS) {
    const path = MODULE_PATH[topic.module] || '/';
    for (let v = 0; v < QUESTION_TEMPLATES.length; v++) {
      if (articles.length >= OPERATIONAL_FAQ_TARGET) break outer;
      const questionPhrase = QUESTION_TEMPLATES[v](topic.action);
      const id = `op-${topic.module}-${String(index).padStart(4, '0')}`;
      const keywords = [
        questionPhrase,
        topic.action,
        topic.title.toLowerCase(),
        topic.module,
        ...(topic.extraKeywords || []),
        `variant ${v}`,
      ];
      articles.push({
        id,
        title: topic.title,
        answer: `${topic.answer}${GUIDE_FOOTER}`,
        steps: [...topic.steps],
        links:
          topic.links.length > 0
            ? topic.links
            : [{ label: topic.module, to: path }],
        keywords,
      });
      index += 1;
    }
  }

  return articles;
}

/** Frozen count for tests and admin UI. */
export const OPERATIONAL_FAQ_COUNT = OPERATIONAL_FAQ_TARGET;
