/** HR staff registration / profile form options. */

export const HR_PAYROLL_GROUPS = [
  { value: 'branch_ops', label: 'Branch staff' },
  { value: 'mining_div', label: 'Mining division' },
  { value: 'hq_admin', label: 'HQ administrative' },
  { value: 'scholarship', label: 'Executive family' },
  { value: 'chairman_staffs', label: 'Household staff' },
];

export const HR_EMPLOYMENT_TYPES = [
  { value: 'permanent', label: 'Permanent' },
  { value: 'contract', label: 'Contract' },
  { value: 'casual', label: 'Casual' },
  { value: 'intern', label: 'Intern' },
];

/** System roles HR may assign when registering staff (excludes admin/md). */
export const HR_REGISTERABLE_ROLES = [
  { value: 'hr_portal_only', label: 'HR portal only (domestic / scholarship / mining)' },
  { value: 'sales_staff', label: 'Sales officer' },
  { value: 'sales_manager', label: 'Branch manager (sales)' },
  { value: 'cashier', label: 'Cashier' },
  { value: 'operations_officer', label: 'Operations officer / Store keeper' },
  { value: 'finance_manager', label: 'Finance manager' },
  { value: 'hr_admin', label: 'HR / Admin' },
  { value: 'gmhr', label: 'GM HR' },
  { value: 'viewer', label: 'Viewer (read-only)' },
];

export const HR_DISCIPLINARY_KINDS = [
  { value: 'warning', label: 'Verbal / written warning' },
  { value: 'query', label: 'Query letter' },
  { value: 'suspension', label: 'Suspension' },
  { value: 'final_warning', label: 'Final warning' },
  { value: 'other', label: 'Other' },
];

export const HR_LEAVE_BANDS = [
  { value: '', label: 'Auto (from job title)' },
  { value: 'junior', label: 'Junior band' },
  { value: 'senior', label: 'Senior band' },
  { value: 'standard', label: 'Standard (maps to junior)' },
  { value: 'executive', label: 'Executive (maps to senior)' },
];

/** Documented when actual pay exceeds salary matrix — see docs/HR/ZAREWA-COMPENSATION-AND-EXCEPTIONS.md */
export const HR_COMPENSATION_VARIANCE_TYPES = [
  { value: 'merit_outstanding', label: 'Merit / outstanding performance' },
  { value: 'scarce_skill_retention', label: 'Scarce skill / retention' },
  { value: 'multi_role_consolidation', label: 'Multi-role consolidation' },
  { value: 'director_emolument', label: 'Director emolument (board)' },
  { value: 'acting_allowance', label: 'Acting role allowance' },
  { value: 'market_adjustment', label: 'Market adjustment' },
  { value: 'special_occasion', label: 'Special occasion' },
];

export const HR_SECONDARY_ROLE_TEMPLATE = {
  designationId: '',
  role: '',
  officeKey: '',
  branchId: '',
  acting: false,
  endDateIso: '',
  notes: '',
};

export const HR_GENDERS = [
  { value: '', label: 'Select gender' },
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
];

export function emptyStaffForm(defaultBranchId = '') {
  return {
    username: '',
    displayName: '',
    password: '',
    roleKey: 'sales_staff',
    branchId: defaultBranchId,
    employeeNo: '',
    jobTitle: '',
    department: '',
    departmentId: '',
    designationId: '',
    jobDescriptionPreview: '',
    employmentType: 'permanent',
    dateJoinedIso: new Date().toISOString().slice(0, 10),
    probationEndIso: '',
    contractEndIso: '',
    lineManagerUserId: '',
    selfServiceEligible: true,
    payrollGroup: 'branch_ops',
    salaryLevel: '',
    salaryStep: '1',
    baseSalaryNgn: '',
    housingAllowanceNgn: '',
    transportAllowanceNgn: '',
    payAdditionNgn: '',
    boardMember: false,
    payeTaxPercent: '',
    payeTaxNgn: '',
    pensionPercentOverride: '',
    taxId: '',
    pensionRsaPin: '',
    bankName: '',
    bankAccountName: '',
    bankAccountNoMasked: '',
    bankAccountNo: '',
    bankCode: '',
    minimumQualification: '',
    academicQualification: '',
    promotionGrade: '',
    trainingSummary: '',
    welfareNotes: '',
    leaveEntitlementBand: '',
    branchChangeReason: '',
    ninNumber: '',
    bvnNumber: '',
    gender: '',
    dateOfBirthIso: '',
    nhisProvider: '',
    nhisMonthlyDeductionNgn: '',
    nextOfKinName: '',
    nextOfKinPhone: '',
    nextOfKinRelationship: '',
    nextOfKinAddress: '',
    nextOfKinAltPhone: '',
    firstName: '',
    middleName: '',
    surname: '',
    personalEmail: '',
    phone: '',
    maritalStatus: '',
    residentialAddress: '',
    stateOfOrigin: '',
    localGovernment: '',
    nationality: 'Nigerian',
    bloodGroup: '',
    employmentStatus: 'active',
    confirmationDateIso: '',
    institution: '',
    courseField: '',
    yearCompleted: '',
    hrInternalNotes: '',
    supervisorName: '',
    salaryStatus: 'active',
    payrollRemarks: '',
    pensionAdministrator: '',
    nhisNumber: '',
    professionalCertificates: '',
    specialConditions: '',
    corporateTitle: '',
    actingEndDateIso: '',
    tenureOverride: false,
    tenureOverrideReason: '',
    secondaryRoles: [],
    compensationVarianceType: '',
    compensationVarianceNotes: '',
    compensationVarianceReviewDueIso: '',
    compensationVarianceMemoRef: '',
    applyMatrixPay: false,
    applyRecommendedRoleKey: false,
    applyMultiRolePermissions: false,
  };
}
